import { autoPrompterParams } from "./bddap.config";
import { handleGeneratePoem } from "../src/server/index";
import {
  Artifact,
  BDDAutoPrompter,
  ApplicationInteractionFlowProps,
} from "bdd-autoprompter";

// a flow has to take in a list of artifacts and conversations
// by the end of a flow each artifact and conversation must have corresponding results
const poemArtifact: Artifact = {
  name: "Poem generation",
  description: "The poem generated by the application",
  variability: 1, // since the temperature of the poem generation is 1 we set the variability to be 1 here too
  getArtifact: handleGeneratePoem,
};

const simplePoetryApplicationFlowProps: ApplicationInteractionFlowProps = {
  autoPrompterParams,
  main: async (autoPrompterParams) => {
    const bddAutoPrompter = await BDDAutoPrompter.initialise(
      autoPrompterParams
    );
    const poemContent = await bddAutoPrompter.fetchArtifactContent(
      poemArtifact
    );
    return bddAutoPrompter;
  },
};

export default [simplePoetryApplicationFlowProps]; // only one flow for this application
